# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
  - name : environment
    displayName : Environment
    type : string
  

variables:
  - name: colour
    ${{ if eq( parameters['environment'], 'develop') }}:
      value: "red"
    ${{ elseif eq( parameters['environment'], 'preproduction' ) }}:
      value: "yellow"
    ${{ else }}:
      value: "purple"

steps:
- script: echo Hello, world! Color is ${{ variables.colour }}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project, Inluding the approvals now.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
