# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
  - name : environment
    displayName : Environment
    type : string
  

variables:
  - ${{ if eq( parameters['environment'], 'develop') }}:
    #- group: Cloud.Automation.Containers.Pipeline.prod
    - name: Environment
      value: Prod
  - ${{ elseif eq( parameters['environment'], 'preproduction' ) }}:
    #- group: Cloud.Automation.Containers.Pipeline.preprod
    - name: Environment
      value: PreProd
  - ${{ else }}:
    #- group: Cloud.Automation.Containers.Pipeline.development
    - name: Environment
      value: Dev
  - name: AgentSource
    value: '1'


steps:
- script: echo Hello, world! Environment is ${{ variables.Environment }} and ${{ variables.AgentSource }}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project, Inluding the approvals now.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
